name: CI
run-name: ssg blog deploy 
on:
  push:
    

jobs:
  build:
    runs-on: ubuntu-latest
    environment: deploy
    steps:

      - name: Clone the repo 
        run: git clone https://github.com/misopog/blog src/ -b main
      
      - name: Create the dst folder
        run: mkdir dst
        
      - name: Install ssg
        run: curl -sLO https://rgz.ee/bin/ssg && chmod 777 ssg 

      - name: Install lowdown
        run: sudo apt install lowdown
      
      - name: Build the website
        run: ./ssg src dst 'blog' 'https://blog.misopog.xyz'
      
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          branch: gh-pages
          folder: dst
