name: deploy to gh pages
permissions:
  contents: write

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: install dependencies (tidy, build tools, debug tools)
        run: |
          sudo apt-get update
          sudo apt-get install -y tidy make gcc gdb valgrind

      - name: build with debug symbols
        run: |
          make

      - name: enable core dumps
        run: |
          ulimit -c unlimited
          echo '/tmp/core.%e.%p' | sudo tee /proc/sys/kernel/core_pattern

      - name: run ./blog and catch segfault
        run: |
          ./blog || (
            echo "Segmentation fault detected!"
            COREFILE=$(ls /tmp/core.* 2>/dev/null || true)
            if [ -n "$COREFILE" ]; then
              echo "Core file: $COREFILE"
              gdb -batch -ex "bt" ./blog "$COREFILE"
            else
              echo "No core file found."
            fi
            exit 1
          )

      - name: run with Valgrind (optional diagnostics)
        run: |
          valgrind --leak-check=full --track-origins=yes ./blog || true

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: output
