name: deploy to gh pages
permissions:
    contents: write

on:
    push:
        branches:
            - master

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest

        steps:
              - name: checkout repository
                uses: actions/checkout@v4
        
              - name: install tidy-html and build tools
                run: |
                  sudo apt-get update
                  sudo apt-get install -y tidy make gcc
        
              - name: build with make and gcc
                run: make
        
              - name: run make cleanrun
                run: make cleanrun
        
              - name: deploy
                uses: JamesIves/github-pages-deploy-action@v4
                with:
                  folder: output